[2025-11-01T00:52:23.496+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-11-01T00:52:23.547+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: avito_minimal_scrape_to_iceberg.run_scraper scheduled__2025-10-31T23:45:00+00:00 [queued]>
[2025-11-01T00:52:23.559+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: avito_minimal_scrape_to_iceberg.run_scraper scheduled__2025-10-31T23:45:00+00:00 [queued]>
[2025-11-01T00:52:23.560+0100] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-11-01T00:52:23.578+0100] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_scraper> on 2025-10-31 23:45:00+00:00
[2025-11-01T00:52:23.588+0100] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'avito_minimal_scrape_to_iceberg', 'run_scraper', 'scheduled__2025-10-31T23:45:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/avito_pipeline.py', '--cfg-path', '/tmp/tmphrvgxx5e']
[2025-11-01T00:52:23.592+0100] {standard_task_runner.py:91} INFO - Job 113: Subtask run_scraper
[2025-11-01T00:52:23.593+0100] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=714) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-11-01T00:52:23.594+0100] {standard_task_runner.py:64} INFO - Started process 715 to run task
[2025-11-01T00:52:23.674+0100] {task_command.py:426} INFO - Running <TaskInstance: avito_minimal_scrape_to_iceberg.run_scraper scheduled__2025-10-31T23:45:00+00:00 [running]> on host 840b98c7ef92
[2025-11-01T00:52:23.791+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='avito' AIRFLOW_CTX_DAG_ID='avito_minimal_scrape_to_iceberg' AIRFLOW_CTX_TASK_ID='run_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T23:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-31T23:45:00+00:00'
[2025-11-01T00:52:23.792+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-11-01T00:52:23.811+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-11-01T00:52:23.813+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec -i avito-scraper bash -lc "PYTHONPATH=/app/src python /app/src/Pipeline/extract/avito_producer.py --mode louer --pages 1 --limit 10 --bootstrap kafka:9092 --topic realestate.avito.raw"']
[2025-11-01T00:52:23.824+0100] {subprocess.py:86} INFO - Output:
[2025-11-01T00:52:24.066+0100] {subprocess.py:93} INFO - python: can't open file '/app/src/Pipeline/extract/avito_producer.py': [Errno 2] No such file or directory
[2025-11-01T00:52:24.077+0100] {subprocess.py:97} INFO - Command exited with return code 2
[2025-11-01T00:52:24.078+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-11-01T00:52:24.096+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-11-01T00:52:24.105+0100] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=avito_minimal_scrape_to_iceberg, task_id=run_scraper, run_id=scheduled__2025-10-31T23:45:00+00:00, execution_date=20251031T234500, start_date=20251031T235223, end_date=20251031T235224
[2025-11-01T00:52:24.128+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 113 for task run_scraper (Bash command failed. The command returned a non-zero exit code 2.; 715)
[2025-11-01T00:52:24.174+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-11-01T00:52:24.224+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-11-01T00:52:24.229+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
